name: report2

on:
  push:
    branches: [ 'master' , 'dev' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install csvkit
      run: |
        sudo apt update
        sudo apt install -y csvkit

    - name: Install latex and dependencies
      run: sudo apt install -y texlive-latex-extra texlive-science latexmk curl

    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    
    - name: build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

    - name: Make analysis (discard-dfs)
      run: |
        cd analysis/discard-dfs
        make -f discard-dfs.mk

    - name: Make analysis (further-analysis)
      run: |
        cd analysis/further-analysis
        make -f further-analysis.mk

    - name: report2
      run: |
        cd doc/report
        latexmk --shell-escape iart_proj1_final.tex -pdf

    - name: Upload delivery2 report
      uses: actions/upload-artifact@v2
      with:
        name: iart_proj1_final.pdf
        path: doc/report/iart_proj1_final.pdf
